# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

source 'git@git.silvrr.com:iOS/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target '__ProjectName__' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


end
