platform :ios, '9.0'
use_frameworks!

source 'https://gitlab.com/aastocks/ios/public/aapodspec.git'
source 'https://gitlab.com/aastocks/aapodspec.git'
source 'https://github.com/CocoaPods/Specs.git'

target '__ProjectName___Example' do

  pod '__ProjectName__', :path => '../'

  # pod 'Base', :path => '../'
  # pod 'Network', '~> 0.1.0'

  # target '__ProjectName___Tests' do
  #   inherit! :search_paths
  #
  #
  # end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
