platform :ios, '8.0'

source 'git@git.silvrr.com:iOS/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target '__ProjectName___Example' do
  use_frameworks!
  
  # pod 'Base', :path => '../'
  # pod 'Network', '~> 0.1.0'

end
